os: linux
dist: bionic

language: python
python:
  - "3.9"

cache:
  pip: true
  directories:
    - "${HOME}/.platformio"
    - "${TRAVIS_BUILD_DIR}/.pio"

install:
  - pip install -U platformio
  - platformio update

script:
  - make CI
