language: python
python:
  - "3.8"

sudo: off
cache:
  directories:
    - "${HOME}/.platformio"
    - "${TRAVIS_BUILD_DIR}/.pio"

install:
  - pip install -U platformio
  - platformio update

script:
  - make CI
